### ISSUE TITLE
BungeeCord inclusion

### ISSUE THREAD

**Issue by Proximyst** [AlessioDP/ADP-Core#2]
When shadowjarring this core, one also includes the _entirety_ of the BungeeCord software. This is in absolutely NO way required and only explodes the file size.

**Comment by AlessioDP** [comment]
I already made a lot of changes in local and I do not have this problem ;)

Jars exported are correct, the only package that is shadowed is "com.alessiodp.core", instead if you mean that BungeeCord software is included in api/implementation/compile, that is correct. In my plugins I directly get Bukkit/BungeeCord by ADP Core instead of adding them one by one.
